PersEmails/ViewModels/Persons/EditPersonViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace PersEmails.ViewModels.Persons
{
    public class EditPersonViewModel
    {
        public int Id { get; set; }
        [StringLength(50)]
        public string Name { get; set; }
        [StringLength(50)]
        public string Surname { get; set; }
        public string? Description { get; set; }
    }
}

PersEmails/ViewModels/Persons/PersonDataViewModel.cs
using PersEmails.Application.Emails;
using PersEmails.Application.Persons;

namespace PersEmails.ViewModels.Persons
{
    public class PersonDataViewModel
    {
        public PersonDto Person { get; set; }
        public IList<EmailDto> Emails { get; set; }
    }
}

PersEmails/ViewModels/Persons/PersonListViewModel.cs
using PersEmails.Application.Persons.Queries;

namespace PersEmails.ViewModels.Persons
{
    public class PersonListViewModel : PageableViewModel
    {
        public IList<PersonWithEmailAddressDto> Persons { get; set; }
    }
}

PersEmails/Controllers/EmailsController.cs
using Microsoft.AspNetCore.Mvc;
using PersEmails.Application.Emails.Queries;
using PersEmails.Application.Emails.Commands;
using PersEmails.Application.Persons.Queries;
using PersEmails.ViewModels.Emails;

namespace PersEmails.Controllers
{
    public class EmailsController : BaseController
    {
        private int _pageSize = 10;

        [HttpGet]
        public IActionResult Index([FromQuery] int? page)
        {
            int pageNumber = page ?? 1;
            var emails = QueryService.Execute(new GetEmailsQuery { PageNumber = pageNumber, PageSize = _pageSize });
            var viewModel = new EmailListViewModel
            {
                Emails = emails,
                PageSize = _pageSize,
                PageNumber = pageNumber,
                ItemsCount = emails.Count
            };
            return View(viewModel);
        }

        [HttpGet]
        public IActionResult Add(int personId) 
        {
            var person = QueryService.Execute(new GetPersonQuery { Id = personId });
            if(person == null)
                return Error("Person not found.");

            return View(new EmailDataViewModel
            {
                PersonId = person.Id,
                PersonName = person.Name,
                PersonSurname = person.Surname
            });
        }

        [HttpPost]
        public IActionResult SaveEmail(EmailDataViewModel email)
        {
            var result = CommandService.Execute(new AddEmailToPersonCommand
            {
                EmailAddress = email.EmailAddress,
                PersonId = email.PersonId
            });
            if (result == 1)
            {
                return RedirectToAction("Person", "Persons", new { id = email.PersonId });
            }

            return Error("Email saving failed.");
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var result = CommandService.Execute(new DeleteEmailCommand { Id = id });
            if(result == 1)
            {
                return Redirect(Request.Headers["Referer"].ToString());
            }

            return Error("No email deleted.");
        }
    }
}

PersEmails/Controllers/PersonsController.cs
using Microsoft.AspNetCore.Mvc;
using PersEmails.Application.Persons.Commands;
using PersEmails.Application.Emails.Queries;
using PersEmails.Application.Persons.Queries;
using PersEmails.ViewModels.Persons;

namespace PersEmails.Controllers
{
    public class PersonsController : BaseController
    {
        private int _pageSize = 6;

        [HttpGet]
        public async Task<IActionResult> Index([FromQuery] int? page)
        {
            int pageNumber = page ?? 1;
            var persons = await QueryService.ExecuteAsync(new GetPersonsQuery { PageNumber = pageNumber, PageSize = _pageSize });
            var viewModel = new PersonListViewModel
            {
                Persons = persons,
                PageSize = _pageSize,
                PageNumber = pageNumber,
                ItemsCount = persons.Count
            };

            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Person(int id)
        {
            var viewModel = new PersonDataViewModel
            {
                Person = QueryService.Execute(new GetPersonQuery { Id = id }),
                Emails = await QueryService.ExecuteAsync(new GetPersonEmailsQuery { Id = id })
            };

            return View(viewModel);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View(new EditPersonViewModel());
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var person = QueryService.Execute(new GetPersonQuery { Id = id });
            if (person == null)
                return Error("Person not found.");

            return View(new EditPersonViewModel
            {
                Id = person.Id,
                Name = person.Name,
                Surname = person.Surname,
                Description = person.Description
            });
        }

        [HttpPost]
        public async Task<IActionResult> SavePerson(EditPersonViewModel person)
        {
            var result = person.Id == 0
                ? await Task.Run(() => CommandService.Execute(new AddPersonCommand
                    {
                        Name = person.Name,
                        Surname = person.Surname,
                        Description = person.Description
                    }))
                : await CommandService.ExecuteAsync(new SavePersonCommand
                    {
                        Id = person.Id,
                        Name = person.Name,
                        Surname = person.Surname,
                        Description = person.Description
                    })
            ;
            if (result == 1)
            {
                return RedirectToAction("Index");
            }

            return Error("Person saving failed.");
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var result = await CommandService.ExecuteAsync(new DeletePersonCommand { Id = id });
            if (result > 0)
            {
                return RedirectToAction("Index");
            }

            return Error("No person deleted.");
        }
    }
}

PersEmails/Views/Persons/Add.cshtml
@using PersEmails.ViewModels.Persons;
@model EditPersonViewModel
@{
    ViewData["Title"] = "Add person";
}

<h2>Add new person</h2>

<form asp-controller="Persons" asp-action="SavePerson" method="post">

    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <label asp-for="Name">Name:</label>
    <input class="form-control" type="text" asp-for="Name" size="50" maxlength="50" />
    <span asp-validation-for="Name" style="color: red;"></span>
    <br />
    <label asp-for="Surname">Surname:</label>
    <input class="form-control" type="text" asp-for="Surname" size="50" maxlength="50" />
    <span asp-validation-for="Surname" style="color: red;"></span>
    <br />
    <label asp-for="Description">Description:</label>
    <textarea class="form-control" asp-for="Description" cols="50" rows="10"></textarea>
    <br />

    <button class="btn btn-secondary" type="submit">Save person</button>
    <button class="btn btn-outline-secondary" type="button" onclick="history.back()">Cancel</button>

</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial.cshtml" />
}

PersEmails/Views/Persons/Edit.cshtml
@using PersEmails.ViewModels.Persons;
@model EditPersonViewModel
@{
    ViewData["Title"] = "Edit perrson data";
}

<h2>Edit details of @Html.DisplayFor(model => model.Name) @Html.DisplayFor(model => model.Surname)</h2>

<form asp-controller="Persons" asp-action="SavePerson" method="post">
    
    <label asp-for="Name">Name:</label>
    <input class="form-control" type="text" asp-for="Name" size="50" maxlength="50" />
    <span asp-validation-for="Name" style="color: red;"></span>
    <br />
    <label asp-for="Surname">Surname:</label>
    <input class="form-control" type="text" asp-for="Surname" size="50" maxlength="50" />
    <span asp-validation-for="Surname" style="color: red;"></span>
    <br />
    <label asp-for="Description">Description:</label>
    <textarea class="form-control" asp-for="Description" cols="50" rows="10"></textarea>
    <input type="hidden" asp-for="Id" />
    <br />

    <button class="btn btn-secondary" type="submit">Save person</button>
    <button class="btn btn-outline-secondary" type="button" onclick="history.back()">Cancel</button>

</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial.cshtml" />
}

PersEmails/Views/Persons/Index.cshtml
@using PersEmails.ViewModels.Persons;
@model PersonListViewModel
@{
    ViewData["Title"] = "List of persons";
}

<h2>Persons</h2>

<table class="col-10 table">
    <tr style="background-color:lightgray">
        <th class="col-1"> surname </th>
        <th class="col-1"> first&nbsp;name </th>
        <th class="col-3"> email </th>
        <th class="col-4"> description </th>

        <th class="col-1"> </th>
        <th class="col-1"> </th>
        <th class="col-1"> </th>
    </tr>

    @foreach (var item in Model.Persons) {
        <tr>
            <td class="col-1" style="background-color:whitesmoke"> @Html.DisplayFor(i => item.Surname) </td>
            <td class="col-1" style="background-color:whitesmoke"> @Html.DisplayFor(i => item.Name) </td>
            <td class="col-3"> @Html.DisplayFor(i => item.EmailAddress) </td>
            <td class="col-4" style="background-color:whitesmoke"> @Html.DisplayFor(i => item.Description) </td>

            <td class="col-1 text-center"> <a class="btn btn-outline-secondary" asp-action="Person" asp-route-id="@item.Id">Details</a> </td>
            <td class="col-1 text-center"> <a class="btn btn-outline-secondary" asp-action="Edit" asp-route-id="@item.Id">Edit</a> </td>
            <td class="col-1 text-center"> <a class="btn btn-outline-danger" asp-action="Delete" asp-route-id="@item.Id">Delete</a> </td>
        </tr>
    }
</table>

<partial name="../Shared/_Paginator.cshtml" model="@Model" />

<br />
<br />
<a class="btn btn-secondary" asp-controller="Persons" asp-action="Add">Add person</a>

PersEmails/Views/Persons/Person.cshtml
@using PersEmails.ViewModels.Persons;
@model PersonDataViewModel
@{
    ViewData["Title"] = "Person's data";
}

<h2>@Html.DisplayFor(model => model.Person.Name) @Html.DisplayFor(model => model.Person.Surname) data:</h2>

<dl class="row">
    <dt>@Html.DisplayNameFor(model => model.Person.Name)</dt>
    <dd class="text-secondary"> @Html.DisplayFor(model => model.Person.Name)</dd>

    <dt>@Html.DisplayNameFor(model => model.Person.Surname)</dt>
    <dd class="text-secondary"> @Html.DisplayFor(model => model.Person.Surname)</dd>

    <dt>@Html.DisplayNameFor(model => model.Person.Description)</dt>
    <dd class="text-secondary"> @Html.DisplayFor(model => model.Person.Description)</dd>
</dl>

<h2>Emails:</h2>

<div class="col-6">
    <partial name="_PersonEmails.cshtml" model="@Model.Emails" />
</div>

<a class="btn btn-secondary" asp-controller="Emails" asp-action="Add" asp-route-personId="@Model.Person.Id">Add email</a>
<a class="btn btn-outline-secondary" asp-controller="Persons" asp-action="Index">Cancel</a>

PersEmails/Views/Persons/_PersonEmails.cshtml
@model IList<PersEmails.Application.Emails.EmailDto>

<table class="table">
    <tr><th></th><th></th></tr>
@foreach (var item in Model)
{
    <tr>
        <td class="col-6">@Html.DisplayFor(i => item.EmailAddress)</td>
        <td class="col-4 text-start">
            <a class="btn btn-outline-danger" asp-controller="Emails" asp-action="Delete" asp-route-id="@item.Id">Delete email</a>
        </td>
    </tr>
}
</table>